name: build docker-prod-images

on:
  release:
    types: [created]

jobs:
  build-backend-image-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version
        uses: actions/github-script@v6
        id: set-version
        with:
          result-encoding: string
          script: return context.payload.release.tag_name.replace('v', '')
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/hs-kuniookita/b-okr-backend:latest
            ghcr.io/hs-kuniookita/b-okr-backend:${{steps.set-version.outputs.result}}
  build-frontend-image-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update version number in package.json
        run: npm version ${{needs.get-version.outputs.version}}
        working-directory: ./frontend
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version
        uses: actions/github-script@v6
        id: set-version
        with:
          result-encoding: string
          script: return context.payload.release.tag_name.replace('v', '')
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/hs-kuniookita/b-okr-frontend:latest
            ghcr.io/hs-kuniookita/b-okr-frontend:${{steps.set-version.outputs.result}}
